databases:
  - name: store-db
    databaseName: store_db
    user: store_user

services:
  - type: web
    name: store-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn store_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: store-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://aqib11234.github.io"
