# Generated by Django 5.0.1 on 2025-06-01 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
