# Generated by Django 5.0.1 on 2025-06-18 07:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0004_purchaseinvoice_amount_paid_purchaseinvoice_is_loan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
