# Generated by Django 5.0.1 on 2025-06-22 11:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_accounttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid so far",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="is_loan",
            field=models.BooleanField(
                default=False, help_text="Whether this sale is on loan/credit"
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Fully Paid"),
                    ("partial", "Partially Paid"),
                    ("unpaid", "Unpaid"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="remaining_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Remaining amount to be paid",
                max_digits=12,
            ),
        ),
        migrations.CreateModel(
            name="SalesLoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payments",
                        to="inventory.salesinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
