# Generated by Django 5.2.5 on 2025-08-20 11:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_salesinvoice_amount_paid_salesinvoice_is_loan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance (positive = customer owes us)', max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, help_text='Total sales amount to this customer', max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, help_text='Total payments received from this customer', max_digits=12)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maximum credit allowed for this customer', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='inventory.customer')),
            ],
            options={
                'ordering': ['customer__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment Received'), ('return', 'Sale Return'), ('discount', 'Discount Given'), ('interest', 'Interest Charged'), ('adjustment', 'Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.customerledger')),
                ('reference_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salesinvoice')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salesloanpayment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance (positive = we owe supplier)', max_digits=12)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, help_text='Total purchase amount from this supplier', max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, help_text='Total payments made to this supplier', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='inventory.supplier')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment Made'), ('return', 'Purchase Return'), ('discount', 'Discount Received'), ('interest', 'Interest Charged'), ('adjustment', 'Balance Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.supplierledger')),
                ('reference_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseinvoice')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseloanpayment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
